export const weatherCodeMap: Record<number, { main: string; description: string; icon: string }> = {
  0: { main: 'Clear', description: 'Trời quang đãng', icon: '01d' },
  1: { main: 'Mainly clear', description: 'Gần như quang đãng', icon: '02d' },
  2: { main: 'Partly cloudy', description: 'Có mây từng phần', icon: '03d' },
  3: { main: 'Overcast', description: 'Nhiều mây', icon: '04d' },
  45: { main: 'Fog', description: 'Sương mù', icon: '50d' },
  48: { main: 'Depositing rime fog', description: 'Sương mù đóng băng', icon: '50d' },
  51: { main: 'Drizzle', description: 'Mưa phùn nhẹ', icon: '09d' },
  53: { main: 'Drizzle', description: 'Mưa phùn', icon: '09d' },
  55: { main: 'Drizzle', description: 'Mưa phùn nặng', icon: '09d' },
  56: { main: 'Freezing Drizzle', description: 'Mưa phùn đóng băng nhẹ', icon: '13d' },
  57: { main: 'Freezing Drizzle', description: 'Mưa phùn đóng băng nặng', icon: '13d' },
  61: { main: 'Rain', description: 'Mưa nhẹ', icon: '10d' },
  63: { main: 'Rain', description: 'Mưa vừa', icon: '10d' },
  65: { main: 'Rain', description: 'Mưa nặng', icon: '10d' },
  66: { main: 'Freezing Rain', description: 'Mưa đóng băng nhẹ', icon: '13d' },
  67: { main: 'Freezing Rain', description: 'Mưa đóng băng nặng', icon: '13d' },
  71: { main: 'Snow fall', description: 'Tuyết rơi nhẹ', icon: '13d' },
  73: { main: 'Snow fall', description: 'Tuyết rơi vừa', icon: '13d' },
  75: { main: 'Snow fall', description: 'Tuyết rơi nặng', icon: '13d' },
  77: { main: 'Snow grains', description: 'Hạt tuyết', icon: '13d' },
  80: { main: 'Rain showers', description: 'Mưa rào nhẹ', icon: '09d' },
  81: { main: 'Rain showers', description: 'Mưa rào vừa', icon: '09d' },
  82: { main: 'Rain showers', description: 'Mưa rào nặng', icon: '09d' },
  85: { main: 'Snow showers', description: 'Mưa tuyết nhẹ', icon: '13d' },
  86: { main: 'Snow showers', description: 'Mưa tuyết nặng', icon: '13d' },
  95: { main: 'Thunderstorm', description: 'Dông', icon: '11d' },
  96: { main: 'Thunderstorm', description: 'Dông nhẹ', icon: '11d' },
  99: { main: 'Thunderstorm', description: 'Dông nặng', icon: '11d' },
}; 